### ISSUE TITLE
Errorr during srarting the client [unexpected keyword argument 'update_workers']

### ISSUE THREAD

**Issue by vovoka** [vtr0n/TelegramTUI#35]
Errorr during srarting the client:
```
$ ./telegramTUI

>>> Traceback (most recent call last):
  File "./telegramTUI", line 2, in <module>
    from src.ui import App
  File "/home/vk/Code/Python/Telegram-bots/TelegramTUI/TelegramTUI/src/ui.py", line 2, in <module>
    from src.MainForm import MainForm
  File "/home/vk/Code/Python/Telegram-bots/TelegramTUI/TelegramTUI/src/MainForm.py", line 4, in <module>
    from src.telegramApi import client
  File "/home/vk/Code/Python/Telegram-bots/TelegramTUI/TelegramTUI/src/telegramApi.py", line 200, in <module>
    client = TelegramApi()
  File "/home/vk/Code/Python/Telegram-bots/TelegramTUI/TelegramTUI/src/telegramApi.py", line 46, in __init__
    spawn_read_thread=True, proxy=proxy)
TypeError: __init__() got an unexpected keyword argument 'update_workers'
```

**Comment by Tylerwbrown** [comment]
I get this as well after installing all the dependencies.

**Comment by Tylerwbrown** [comment]
Figured it out, even though I copy pasted the command, the wrong version of telethon was downloaded. I had to use pip3 to uninstall and reinstall the proper version (specified in the readme).

There was another error (no module named Image), this time occurring after the login message was sent. Doing `pip3 install Pillow` fixed that.
