### ISSUE TITLE
invalid literal for int()

### ISSUE THREAD

**Issue by aryadovoy** [vtr0n/TelegramTUI#37]
Hello. Cannot start.
```
user@desktop:~/TelegramTUI$ ./telegramTUI
Traceback (most recent call last):
  File "./telegramTUI", line 2, in <module>
    from src.ui import App
  File "/home/user/TelegramTUI/src/ui.py", line 2, in <module>
    from src.MainForm import MainForm
  File "/home/user/TelegramTUI/src/MainForm.py", line 4, in <module>
    from src.telegramApi import client
  File "/home/user/TelegramTUI/src/telegramApi.py", line 200, in <module>
    client = TelegramApi()
  File "/home/user/TelegramTUI/src/telegramApi.py", line 46, in __init__
    spawn_read_thread=True, proxy=proxy)
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_client.py", line 199, in __init__
    **kwargs
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_bare_client.py", line 111, in __init__
    self.api_id = int(api_id)
ValueError: invalid literal for int() with base 10: "*728013'"
```

**Comment by aryadovoy** [comment]
Sorry. Incorrect data with *****.
