### ISSUE TITLE
OSError: libaa.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by hanyoonLDA** [vtr0n/TelegramTUI#47]
Hey all,

I can install TGTUI fine with pipenv as well as pip, but when I try to launch the client I keep getting this error:

`OSError: libaa.so.1: cannot open shared object file: No such file or directory`

Any idea what's wrong? I tried both Python 3.6, and 3.7.

Here's the full:

```
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/TelegramTUI-y2cX0UwA/bin/telegramtui", line 11, in <module>
    load_entry_point('telegramtui', 'console_scripts', 'telegramtui')()
  File "/root/.local/share/virtualenvs/TelegramTUI-y2cX0UwA/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/root/.local/share/virtualenvs/TelegramTUI-y2cX0UwA/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/root/.local/share/virtualenvs/TelegramTUI-y2cX0UwA/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/root/.local/share/virtualenvs/TelegramTUI-y2cX0UwA/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/TelegramTUI/telegramtui/__main__.py", line 1, in <module>
    from telegramtui.src.ui import App
  File "/home/TelegramTUI/telegramtui/src/ui.py", line 2, in <module>
    from telegramtui.src.MainForm import MainForm
  File "/home/TelegramTUI/telegramtui/src/MainForm.py", line 6, in <module>
    from telegramtui.src import messageBox
  File "/home/TelegramTUI/telegramtui/src/messageBox.py", line 5, in <module>
    from telegramtui.src import aalib
  File "/home/TelegramTUI/telegramtui/src/aalib.py", line 4, in <module>
    import aalib
  File "/root/.local/share/virtualenvs/TelegramTUI-y2cX0UwA/lib/python3.7/site-packages/aalib.py", line 29, in <module>
    libaa = ctypes.CDLL('libaa.so.1')
  File "/usr/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libaa.so.1: cannot open shared object file: No such file or directory
```

**Comment by murilobsd** [comment]
Please, install [http://aa-project.sourceforge.net/aalib/](http://aa-project.sourceforge.net/aalib/)

**Comment by vtr0n** [comment]
Try to install aalib by pip:
```pip3 install python-aalib```

**Comment by murilobsd** [comment]
> Try to install aalib by pip:
> `pip3 install python-aalib`

@vtr0n In the operating system (**OpenBSD**) that I use _aalib_ has not been ported **yet**, I [fork](https://github.com/murilobsd/TelegramTUI) to leave aalib import **optional**. During the week I see if I can import aalib.
 
Thanks for the great work.

**Comment by vtr0n** [comment]
I remember that I have the same issue in OS X.
I think you can modify [this](https://github.com/vtr0n/TelegramTUI/blob/master/telegramtui/src/aalib.py) file to solve the problem.

**Comment by murilobsd** [comment]
I'm sorry I did not see this file, I will change it and see how it goes.

**Comment by hanyoonLDA** [comment]
> Try to install aalib by pip:
> `pip3 install python-aalib`

Seems like aalib was installed properly? I am using py3.7 with pipenv.

`Requirement already satisfied: python-aalib in /root/.local/share/virtualenvs/TelegramTUI-y2cX0UwA/lib/python3.7/site-packages (0.3.2)`

Same error:

```
File "/home/TelegramTUI/telegramtui/src/messageBox.py", line 5, in <module>
    from telegramtui.src import aalib
  File "/home/TelegramTUI/telegramtui/src/aalib.py", line 4, in <module>
    import aalib
  File "/root/.local/share/virtualenvs/TelegramTUI-y2cX0UwA/lib/python3.7/site-packages/aalib.py", line 29, in <module>
    libaa = ctypes.CDLL('libaa.so.1')
  File "/usr/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libaa.so.1: cannot open shared object file: No such file or directory
```

**Comment by vtr0n** [comment]
@hanyoonLDA what OS do you use?

**Comment by hanyoonLDA** [comment]
@vtr0n Ubuntu 18 on this machine.

**Comment by vtr0n** [comment]
@hanyoonLDA I'll fix this a little bit later.
Please, try to install aalib another way:
```
sudo apt-get install aalib
sudo apt-get install python-aalib
```

**Comment by hanyoonLDA** [comment]
> ```
> sudo apt-get install python-aalib
> ```

heyohhhh, that worked. Weird. Thank you!
